[package]
name = "hash-loop"
version = "0.1.0"
authors = ["gesslerpd <gesslerpd@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
structopt = "*"
sha1 = "*"
rayon = "*"
bytemuck = { version = "1", features = ["derive"] }
cudarc = { version = "0.19", features = ["cuda-13000", "driver", "nvrtc"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
